# Fake News Detector

## Importing the dependencies

In [2]:
import numpy as np
import pandas as pd
import re
# stopwords that doesn't add value to a paragraph(where what, is all else)
from nltk.corpus import stopwords
import nltk
# gives root word for particular word
from nltk.stem.porter import PorterStemmer
# for converting text to feature vector
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
# 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
# Stemming is the processing of taking the word and removing prefix and suffix of word and returns the root word.

In [3]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/ishukumar5663/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [4]:
# printing the stopwords
print(stopwords.words("english"))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

## Data Pre-processing

In [5]:
# Load dataset into pandas DataFrame
news_dataset = pd.read_csv("./train.csv")

In [6]:
news_dataset.shape

(20800, 5)

In [7]:
news_dataset.head()

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1

In [8]:
#  counting the number of missing values in the dataset
news_dataset.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [9]:
# replacing the null values with empty string

news_dataset = news_dataset.fillna("")

In [10]:
# merging the author name, title and text
news_dataset['content'] = news_dataset['author'] + " " + news_dataset['title'] + ' ' + news_dataset["text"]

In [11]:
news_dataset

,id,title,author,text,label,content
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1,Darrell Lucus House Dem Aide: We Didn’t Even S...
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0,"Daniel J. Flynn FLYNN: Hillary Clinton, Big Wo..."
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1,Consortiumnews.com Why the Truth Might Get You...
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1,Jessica Purkiss 15 Civilians Killed In Single ...
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1,Howard Portnoy Iranian woman jailed for fictio...
...,...,...,...,...,...,...
20795,20795,Rapper T.I.: Trump a ’Poster Child For White S...,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...,0,Jerome Hudson Rapper T.I.: Trump a ’Poster Chi...
20796,20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",Benjamin Hoffman,When the Green Bay Packers lost to the Washing...,0,"Benjamin Hoffman N.F.L. Playoffs: Schedule, Ma..."
20797,20797,Macy’s Is Said to Receive Takeover Approach by...,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...,0,Michael J. de la Merced and Rachel Abrams Macy...
20798,20798,"NATO, Russia To Hold Parallel Exercises In Bal...",Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal...",1,"Alex Ansary NATO, Russia To Hold Parallel Exer..."
20799,20799,What Keeps the F-35 Alive,David Swanson,"David Swanson is an author, activist, journa...",1,David Swanson What Keeps the F-35 Alive Davi...

In [12]:
# seperating the data and label
X = news_dataset.drop(columns=["label", "id"], axis=0)
Y = news_dataset["label"]

In [13]:
print(X)
print(Y)

                                                   title  \
0      House Dem Aide: We Didn’t Even See Comey’s Let...
1      FLYNN: Hillary Clinton, Big Woman on Campus - ...
2                      Why the Truth Might Get You Fired
3      15 Civilians Killed In Single US Airstrike Hav...
4      Iranian woman jailed for fictional unpublished...
...                                                  ...
20795  Rapper T.I.: Trump a ’Poster Child For White S...
20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...
20797  Macy’s Is Said to Receive Takeover Approach by...
20798  NATO, Russia To Hold Parallel Exercises In Bal...
20799                          What Keeps the F-35 Alive

                                          author  \
0                                  Darrell Lucus
1                                Daniel J. Flynn
2                             Consortiumnews.com
3                                Jessica Purkiss
4                                 Howard Portnoy
...                                          ...
20795                              Jerome Hudson
20796                           Benjamin Hoffman
20797  Michael J. de la Merced and Rachel Abrams
20798                                Alex Ansary
20799                              David Swanson

                                                    text  \
0      House Dem Aide: We Didn’t Even See Comey’s Let...
1      Ever get the feeling your life circles the rou...
2      Why the Truth Might Get You Fired October 29, ...
3      Videos 15 Civilians Killed In Single US Airstr...
4      Print \nAn Iranian woman has been sentenced to...
...                                                  ...
20795  Rapper T. I. unloaded on black celebrities who...
20796  When the Green Bay Packers lost to the Washing...
20797  The Macy’s of today grew from the union of sev...
20798  NATO, Russia To Hold Parallel Exercises In Bal...
20799    David Swanson is an author, activist, journa...

                                                 content
0      Darrell Lucus House Dem Aide: We Didn’t Even S...
1      Daniel J. Flynn FLYNN: Hillary Clinton, Big Wo...
2      Consortiumnews.com Why the Truth Might Get You...
3      Jessica Purkiss 15 Civilians Killed In Single ...
4      Howard Portnoy Iranian woman jailed for fictio...
...                                                  ...
20795  Jerome Hudson Rapper T.I.: Trump a ’Poster Chi...
20796  Benjamin Hoffman N.F.L. Playoffs: Schedule, Ma...
20797  Michael J. de la Merced and Rachel Abrams Macy...
20798  Alex Ansary NATO, Russia To Hold Parallel Exer...
20799  David Swanson What Keeps the F-35 Alive   Davi...

[20800 rows x 4 columns]
0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 20800, dtype: int64

## Stemming

Stemming is the process of reducing a word to its root word

Ex: Actor, actress, acting --> act (stemming)

In [14]:
port_stem = PorterStemmer()

In [15]:
def stemming(content: str) -> str:
    # exclusion of a-z and A-Z, replace them with space
    stemmed_content = re.sub('[^a-zA-Z]',' ',content)
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words("english")]
    #  just hover over join to understand
    stemmed_content = " ".join(stemmed_content)
    return stemmed_content

In [16]:

#! Need to run once 
news_dataset["content"] = news_dataset['content'].apply(stemming)
news_dataset.to_csv("./model_train.csv")

In [17]:
X.head()

,title,author,text,content
0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus House Dem Aide: We Didn’t Even S...
1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,"Daniel J. Flynn FLYNN: Hillary Clinton, Big Wo..."
2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",Consortiumnews.com Why the Truth Might Get You...
3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,Jessica Purkiss 15 Civilians Killed In Single ...
4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,Howard Portnoy Iranian woman jailed for fictio...

In [18]:
# Reading from saved output
# X = pd.read_csv("./model_x.csv")

In [19]:
# seperating data and label
X = news_dataset["content"].values
Y = news_dataset["label"].values

In [20]:
X,Y

(<StringArray>
 [                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       'darrel lucu hous dem aid even see comey letter jason chaffetz tweet hous dem aid even see comey letter jason chaffetz tweet darrel lucu octob subscrib jason chaffetz stump american fork utah imag courtesi michael jolley avail creativ common licens apolog keith olbermann doubt worst person world week fbi director jame comey accord hous democrat aid look like also know second worst person well turn comey sent infam letter announc fbi look email may relat hillari clinton email server rank democrat relev committe hear comey found via tweet one republican committe chairmen know comey notifi republican chairmen democrat rank member hous intellig judiciari oversight committe agenc review email recent discov order see contain classifi inform long letter went oversight committe chairman jason chaffetz set polit world ablaz tweet fbi dir inform fbi learn exist email appear pertin investig case reopen jason chaffetz jasoninthehous octob cours know case comey actual say review email light unrel case know anthoni weiner sext teenag appar littl thing fact matter chaffetz utah republican alreadi vow initi raft investig hillari win least two year worth possibl entir term worth appar chaffetz thought fbi alreadi work result tweet briefli roil nation cooler head realiz dud accord senior hous democrat aid misread letter may least chaffetz sin aid told shareblu boss democrat even know comey letter time found check twitter democrat rank member relev committe receiv comey letter republican chairmen fact democrat rank member receiv chairman oversight govern reform committe jason chaffetz tweet made public let see got right fbi director tell chaffetz gop committe chairmen major develop potenti polit explos investig neither chaffetz colleagu courtesi let democrat counterpart know instead accord aid made find twitter alreadi talk daili ko comey provid advanc notic letter chaffetz republican give time turn spin machin may make good theater noth far even suggest case noth far suggest comey anyth grossli incompet tone deaf suggest howev chaffetz act way make dan burton darrel issa look like model respons bipartisanship even decenc notifi rank member elijah cum someth explos trampl basic standard fair know grant like chaffetz answer sit ridicul republican district anchor provo orem cook partisan vote index r gave mitt romney punish percent vote moreov republican hous leadership given full support chaffetz plan fish expedit mean turn hot light textbook exampl hous becom republican control also second worst person world darrel lucu darrel someth graduat univers north carolina consid journalist old school attempt turn member religi right colleg succeed turn religi right worst nightmar charismat christian unapologet liber desir stand scare silenc increas surviv abus three year marriag may know daili ko christian dem nc follow twitter darrelllucu connect facebook click buy darrel mello yello connect',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      'daniel j flynn flynn hillari clinton big woman campu breitbart ever get feel life circl roundabout rather head straight line toward intend destin hillari clinton remain big woman campu leafi liber wellesley massachusett everywher els vote like inaugur dress remaind day way miss havisham forev wore wed dress speak great expect hillari rodham overflow year ago first address wellesley graduat class presid colleg inform gather student need debat far could ascertain spokesman kind like democrat primari minu term unknown even seven sister school glad miss adam made clear speak today us us miss rodham told classmat appoint edger bergen charli mccarthi mortim snerd attend bespectacl granni glass award matronli wisdom least john lennon wisdom took issu previou speaker despit becom first win elect seat u senat sinc reconstruct edward brook came critic call empathi goal protestor critic tactic though clinton senior thesi saul alinski lament black power demagogu elitist arrog repress intoler within new left similar word come republican necessit brief rebutt trust rodham iron observ one word ask class rehears want say everyon came said talk trust talk lack trust us way feel other talk trust bust say say feel permeat gener perhap even understood distrust trust bust certainli bust clinton plan certainli even understand peopl distrust whitewat travelg vast conspiraci benghazi miss email clinton found distrust voic friday load compromis road broaden polit horizon distrust american peopl trump edg percent percent question immedi prior novemb elect stood major reason close horizon clinton describ vanquish support embrac lie con altern fact assault truth reason fail explain american peopl chose lie truth histori major among today know well peopl power invent fact attack question mark begin end free societi offer hyperbol like mani peopl emerg hillari clinton embark upon long strang trip high school goldwat girl wellesley colleg republican presid democrat politician clinton drank time place gave degre significantli went idealist cynic comparison two wellesley commenc address show way back lament long leader view polit art possibl challeng practic polit art make appear imposs possibl big woman campu odd woman white hous wonder current station even possibl point ahead ask septemb may ask presid woman famous dub congenit liar bill safir conclud lie mind get stood elect day like find jilt bride wed day inspir danger delus',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'consortiumnew com truth might get fire truth might get fire octob tension intellig analyst polit policymak alway honest assess desir result latter often overwhelm former iraq war write lawrenc davidson lawrenc davidson might wonder foreign polici maker repeatedli make bad choic insight might drawn follow analysi action play unit state lesson probabl univers back earli spring georg w bush initi invas iraq one key public reason claim countri dictat saddam hussein verg develop nuclear weapon hide weapon mass destruct real reason went beyond charg includ long rang plan regim chang middl east presid georg w bush vice presid dick cheney receiv oval offic brief cia director georg tenet also present chief staff andi card right white hous photo purpos concentr belief iraq becom hostil nuclear power presid bush close associ accept scenario readili short answer bush want inde need believ rational invad iraq first tri connect saddam hussein attack u though never gave stratagem lack evid made difficult ralli american peopl alreadi fixat afghanistan support war baghdad nuclear weapon gambit prove fruit hard evid charg supposedli reliabl wit person exil anti saddam iraqi mani u govern payrol kept tell bush advis nuclear stori true u leadership cadr whose worldview liter demand mortal danger iraq inform order precipit overthrow saddam will tell tale pend atom weapon strong desir believ tale nuclear iraq lower threshold proof likewis repeat assert assum depend iraqi sourc underpin nationwid u campaign gener fear war fever u alli insist unit nation send weapon inspector scour iraq evid nuclear weapon program well chemic biolog weapon inspector could find convinc evid frustrat bush administr soon forc hand march bush launch invas iraq expect occup countri u inspector would sure find evid nuke least stockpil chemic biolog weapon iraqi inform systemat lie social behavior scienc rescu variou u intellig agenc thoroughli shaken affair today year later director manag still tri sort specif tell get true intellig lie one intellig worker put need help protect us armi snake oil salesmen end cia et al market academ assist ahm chalabi head iraqi nation congress key supplier iraqi defector bogu stori hidden wmd partnership forg offic director nation intellig odni serv coordin center sixteen independ u intellig agenc nation academi scienc engin medicin result collabor perman intellig commun studi board coordin program social behavior scienc research might strengthen nation secur despit effort almost certain social behavior scienc cannot give spi agenc want way detect lie better present standard procedur polygraph test interrog even could might well make differ real problem found liar found believ believ simpli true odni leader seem assert u intellig agenc personnel cannot tell often lie case thousand middl echelon intellig worker desk offic specialist know someth close approach truth know pretti well go place like afghanistan iraq syria libya israel palestin elsewher director nation intellig jame clapper right talk presid barack obama oval offic john brennan nation secur aid present photo credit offic director nation intellig therefor someon feed snake oil usual know howev accur grasp thing often avail superior got appoint accept pre structur worldview differ criterion true analyst listen charl gaukel nation intellig council yet anoth organ act meet ground intellig agenc refer search way avoid get taken lie gaukel declar look truth particularli look truth work might mean certainli tell mean histor mean power broker truth must match fit worldview polit ideolog precept fit work intellig specialist send usual accur assess line polici maker often hit roadblock caus group think ideolog blinker know better attitud hand long sell leadership match want believ peddl anyth imaginari iraqi nuke israel western style democraci saudi arabia indispens alli libya liber countri bashar al assad real roadblock peac syria strateg defens initi sdi aka star war world get colder warmer american exception glori list almost endless sad tale tell us want spend million dollar social behavior scienc research improv assess use intellig forget liar want look antidot narrow minded believ policymak seem abl rise ideolog presumpt class presumpt underpin self confid lead us slipperi slope happen way often mani place sourc shakespear determin past prelud elit play destini free capac break structur way see yet middl echelon specialist keep send rel accur assess ladder power hope spring etern',

In [21]:
Y.shape

(20800,)

In [22]:
vectorizer = TfidfVectorizer()
#? converting the textual data to numerical data, assigns a word power that a word appearing number of times and assign inverse power to it, idf is inverse so if a word appearing multiple times doesn't have much important
vectorizer.fit(X)

X = vectorizer.transform(X)

In [23]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5144938 stored elements and shape (20800, 111501)>
  Coords	Values
  (0, 325)	0.04351705682996119
  (0, 521)	0.022974569956367194
  (0, 635)	0.038727100898403345
  (0, 873)	0.01573563765182704
  (0, 922)	0.016392735476282342
  (0, 1298)	0.021078125206502117
  (0, 1610)	0.01797988302277085
  (0, 1886)	0.11545306338629945
  (0, 3022)	0.046620910610995464
  (0, 3042)	0.01902260509613337
  (0, 3377)	0.011797233080872101
  (0, 3743)	0.030879171097770226
  (0, 4156)	0.016679444655381123
  (0, 4260)	0.01942127157583213
  (0, 4306)	0.026424556938478543
  (0, 4588)	0.01769571497502257
  (0, 4772)	0.025939050637307268
  (0, 4822)	0.041683522324264644
  (0, 4839)	0.014401489020964033
  (0, 6421)	0.018224972680710137
  (0, 6964)	0.02064947765731587
  (0, 8556)	0.021643407923861314
  (0, 9072)	0.014237130761490214
  (0, 10846)	0.04758422449372864
  (0, 12251)	0.02777858540400552
  :	:
  (20799, 106830)	0.03658229119526847
  (20799, 106963)	0.04920336424986249
  (20799, 107284)	0.018656595080459182
  (20799, 107318)	0.043134822227799886
  (20799, 107645)	0.01740299562958845
  (20799, 107681)	0.05068455319072
  (20799, 107695)	0.034466748042900446
  (20799, 108347)	0.05068455319072
  (20799, 108602)	0.03651772089101267
  (20799, 108658)	0.02976233207472996
  (20799, 108695)	0.054965853501951864
  (20799, 108697)	0.09840672849972498
  (20799, 108726)	0.018215428043562847
  (20799, 108763)	0.008302289818655216
  (20799, 108800)	0.05068455319072
  (20799, 108911)	0.05068455319072
  (20799, 108935)	0.05068455319072
  (20799, 108963)	0.05068455319072
  (20799, 108977)	0.05068455319072
  (20799, 108991)	0.04563455674829655
  (20799, 109027)	0.05068455319072
  (20799, 109028)	0.05068455319072
  (20799, 109033)	0.05068455319072
  (20799, 109093)	0.05068455319072
  (20799, 109697)	0.03345725922566747

## Splitting from training to test data

In [24]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y ,random_state=2)

## Training the model

In [25]:
model = LogisticRegression()

In [26]:
model.fit(X_train, Y_train)

LogisticRegression()

## Evaluation of model

In [27]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print("Accuracy score on training data: ", training_data_accuracy)

Accuracy score on training data:  0.9785456730769231

In [28]:
X_test_pred = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_pred, Y_test)
print("Accuracy score on test data: ", test_data_accuracy)

Accuracy score on test data:  0.9526442307692308

## Making a predictive system

In [29]:
X_new = X_test[0]

prediction = model.predict(X_new)
#? 1 is fake and 0 is real
if(prediction[0] == 0):
    print("Real News")
else:
    print("Fake news")

print(Y_test[0])

Fake news
1

In [30]:
# Fake news
news = "Donald Trump Sends Out Embarrassing New Year’s Eve Message; This is Disturbing	Donald Trump just couldn t wish all Americans a Happy New Year and leave it at that. Instead, he had to give a shout out to his enemies, haters and  the very dishonest fake news media.  The former reality show star had just one job to do and he couldn t do it. As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year,  President Angry Pants tweeted.  2018 will be a great year for America! As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year. 2018 will be a great year for America!  Donald J. Trump (@realDonaldTrump) December 31, 2017Trump s tweet went down about as welll as you d expect.What kind of president sends a New Year s greeting like this despicable, petty, infantile gibberish? Only Trump! His lack of decency won t even allow him to rise above the gutter long enough to wish the American citizens a happy new year!  Bishop Talbert Swan (@TalbertSwan) December 31, 2017no one likes you  Calvin (@calvinstowell) December 31, 2017Your impeachment would make 2018 a great year for America, but I ll also accept regaining control of Congress.  Miranda Yaver (@mirandayaver) December 31, 2017Do you hear yourself talk? When you have to include that many people that hate you you have to wonder? Why do the they all hate me?  Alan Sandoval (@AlanSandoval13) December 31, 2017Who uses the word Haters in a New Years wish??  Marlene (@marlene399) December 31, 2017You can t just say happy new year?  Koren pollitt (@Korencarpenter) December 31, 2017Here s Trump s New Year s Eve tweet from 2016.Happy New Year to all, including to my many enemies and those who have fought me and lost so badly they just don t know what to do. Love!  Donald J. Trump (@realDonaldTrump) December 31, 2016This is nothing new for Trump. He s been doing this for years.Trump has directed messages to his  enemies  and  haters  for New Year s, Easter, Thanksgiving, and the anniversary of 9/11. pic.twitter.com/4FPAe2KypA  Daniel Dale (@ddale8) December 31, 2017Trump s holiday tweets are clearly not presidential.How long did he work at Hallmark before becoming President?  Steven Goodine (@SGoodine) December 31, 2017He s always been like this . . . the only difference is that in the last few years, his filter has been breaking down.  Roy Schulze (@thbthttt) December 31, 2017Who, apart from a teenager uses the term haters?  Wendy (@WendyWhistles) December 31, 2017he s a fucking 5 year old  Who Knows (@rainyday80) December 31, 2017So, to all the people who voted for this a hole thinking he would change once he got into power, you were wrong! 70-year-old men don t change and now he s a year older.Photo by Andrew Burton/Getty Images.	News	December 31, 2017"
news = stemming(news)
news_tdidf = vectorizer.transform([news])
pred = model.predict(news_tdidf)
print(pred)

[1]

In [33]:
# Riyal News
news = "Duterte berates Canada's Trudeau at end of Philippines summit	MANILA (Reuters) - Philippines President Rodrigo Duterte attacked Canada’s Justin Trudeau at the end of a summit of Asian and Western nations for raising questions about his war on drugs, a topic skirted by other leaders, including U.S. President Donald Trump. At the traditional news conference by the host nation at the end of the summit on Tuesday, Duterte was asked how he had responded to the Canadian prime minister raising the issue of human rights and extra-judicial killings in his anti-drugs drive. “I said I will not explain. It is a personal and official insult,” the Philippines president said in the course of a rambling answer, although he did not refer to Trudeau by name. “I only answer to the Filipino. I will not answer to any other bullshit, especially foreigners. Lay off.” Earlier in the day, Trudeau told a news conference that during his meeting with Duterte “the president was receptive to my comments and it was throughout a very cordial and positive exchange”. Human rights activists had been hoping that leaders at the summit, including Trump, would raise the issue of the thousands of users and small-time pushers killed in the campaign that was launched by Duterte after he took office in mid-2016. His government says the police act in self-defense during drug-busts, but critics say executions are taking place with no accountability. There was no pressure from Trump on the drugs war when he met Duterte on Monday and the U.S. president later said the two had a “great relationship”. A joint statement after the meeting only said the two sides “underscored that human rights and the dignity of human life are essential, and agreed to continue mainstreaming the human rights agenda in their national programs.” Duterte cursed Trump’s predecessor, Barack Obama, last year for raising concerns about the war on drugs and he subsequently declared that he was breaking ties with the United States, a close ally of the Philippines since World War Two. The relationship appears to have got back on track after the bonhomie between him and Trump. Trudeau also said that he raised the issue of the exodus of Rohingya during a meeting with Myanmar leader Aung San Suu Kyi, another sensitive topic bypassed by most other leaders, although he did not mention the Muslim minority by name. “This is a tremendous concern to Canada and to many, many countries around the world,” he said. The government in mostly-Buddhist Myanmar regards the Rohingya as illegal immigrants from Bangladesh and does not recognize the term. Over 600,000 Rohingya have fled to refugee camps in Bangladesh since military clearance operations were launched in response to attacks by Rohingya militants on Aug. 25.  The plight of the Rohingya has brought outrage from around the world and the United Nations has called the operations ethnic cleansing. There have been calls for democracy champion Suu Kyi to be stripped of the Nobel peace prize she won in 1991 because she has not condemned the military’s actions. Some countries in the 10-member Association of Southeast Asian Nations (ASEAN), particularly Muslim-majority Malaysia, have voiced strong concern over the issue recently. However, in keeping with ASEAN’s principle of non-interference in each others’ internal affairs, it appeared to have been put aside at the summit, which brought Southeast Asian nations together with the United States, Russia, Japan, China, India, Australia, New Zealand and Canada. Duterte reported that China had agreed at the summit to work on a code of conduct in the South China Sea with ASEAN nations to ease tensions over disputed claims to the busy and resource-rich waterway. The group also signed agreements on protecting migrant labor and fighting terrorism and cybercrime. Trump skipped the plenary session of the summit because of scheduling delays, but he said his marathon trip to Asia had been a “tremendous” success. He told reporters on Air Force One that he had delivered his prepared remarks during a lunch before the summit meeting.  Trump said at least $300 billion, possibly triple that figure, of deals had been agreed in the trip. He did not elaborate. “We’ve explained that the United States is open for trade but we want reciprocal, we want fair trade for the United States,” he said. Trade and concern about possible protectionism under Trump’s “America First” agenda have come up during his visit to the region, which included stops in Japan, South Korea, China, Vietnam before concluding in the Philippines. After Trump left Manila, a group of Asia-Pacific nations pursuing a separate Beijing-backed trade deal that does not include the United States agreed to “intensify efforts” in 2018 to bring their negotiations to a conclusion. The Regional Comprehensive Economic Partnership (RCEP) appeared to have been given new impetus at the summit by Trump’s withdrawal from the Trans-Pacific Partnership (TPP) trade agreement, to which China is not party. The two trade deals are not mutually exclusive. ASEAN is joined in the RCEP talks by China, India, Australia, New Zealand, Japan and South Korea. 	politicsNews	November 14, 2017"
news = stemming(news)
news_tdidf = vectorizer.transform([news])
pred = model.predict(news_tdidf)
print(pred)

[0]